### ISSUE TITLE
failed install on a clean gstreamer/kaldi build

### ISSUE THREAD

**Issue by jhludwig** [alumae/gst-kaldi-nnet2-online#24] opened 2015-08-25 03:42 UTC
hi, i just did a clean install of gstreamer 1.45 and of kaldi.  the kaldi samples seem to run, including the gstreamer plugin in kadli/src/gst-plugins.

gst-kaldi-nnet2-online builds without error, but doesn't load:
```
john@caseless:~/ws/git/gst-kaldi-nnet2-online/src$ GST_PLUGIN_PATH=. gst-inspect-1.0 kaldinnet2onlinedecoder

(gst-plugin-scanner:17734): GStreamer-WARNING **: Failed to load plugin './libgstkaldionline2.so': ./libgstkaldionline2.so: undefined symbol: _ZN3fst12ReadFstKaldiESs
```
this is happening on two different machines, one native ubuntu, one a vmware vm.  it would appear that the plugin cannot find the fst shared libs.  is there some particular install step that needs to be performed on fst different than the kaldi setup tools suggest?

thanks

**Comment by alumae** [comment] 2015-08-25 13:04
Try setting:
    
   export LD_LIBRARY_PATH=$KALDI_ROOT/tools/openfst/lib

**Comment by jhludwig** [comment] 2015-08-25 17:04
this fails on both my machines.  same message as above.  using c++filt, this symbol resolves to
```
fst::ReadFstKaldi(std::basic_string<char, std::char_traits<char>, std::allocator<char> >)
```
which ultimately resolves to the fst includes.  this all resolves ok at compile time and i can build the plugin with no issue.  but at runtime, if i understand the error, the plugin cannot find the shared fst libraries.  the libs seem to be in the $KALDI_ROOT/tools/openfst/lib dir:

```
john@ubuntu:~/ws/git/kaldi$ ls tools/openfst-1.3.4/lib/
fst             libfstscript.la    libfstscript.so.1.0.0  libfst.so        ..
libfstscript.a  libfstscript.so    libfst.a               libfst.so.1
.               libfstscript.so.1  libfst.la              libfst.so.1.0.0
```

and LD_LIBRARY_PATH is set:

```
john@ubuntu:~/ws/git/kaldi$ printenv | grep LD_LIBRARY_PATH
LD_LIBRARY_PATH=/home/john/ws/git/kaldi/tools/openfst-1.3.4/lib
```

i am wondering if you have openfst installed globally in /usr/local/lib.  or if you have run package config on openfst.  thanks for any tips, appreciate the effort.

**Comment by alumae** [comment] 2015-08-26 02:47
I managed to replicate this problem, it appears that it is caused by some recent change in Kaldi. Working on a fix.

**Comment by alumae** [comment] 2015-08-26 02:53
Pushed a fix.

**Closed by alumae** 2015-08-26 02:53 UTC

**Comment by jhludwig** [comment] 2015-08-26 03:09
perfect, very much appreciated.
