### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by JaimeOsacar** [alumae/gst-kaldi-nnet2-online#94] opened 2019-11-12 10:21 UTC
Hi everyone. I am facing a similar problem as mrlonely001 ( https://github.com/alumae/gst-kaldi-nnet2-online/issues/92 ) . I'm doing the latest commit and this error appears now:

gstkaldinnet2onlinedecoder.cc: In function 'void kaldi::gst_kaldinnet2onlinedecoder_threaded_decode_segment(kaldi::Gstkaldinnet2onlinedecoder*, bool&, int32, kaldi::BaseFloat, kaldi::Vector<float>*)':
gstkaldinnet2onlinedecoder.cc:1373:68: error: no matching function for call to 'kaldi::SingleUtteranceNnet2DecoderThreaded::SingleUtteranceNnet2DecoderThreaded(kaldi::OnlineNnet2DecodingThreadedConfig&, kaldi::TransitionModel&, kaldi::nnet2::AmNnet&, fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >&, kaldi::OnlineNnet2FeaturePipelineInfo&, kaldi::OnlineIvectorExtractorAdaptationState&)'
                                         *(filter->adaptation_state));

How can I fix it?

Thanks for your time and help!

**Comment by alumae** [comment] 2020-09-25 12:12
Duplicate of #99

**Closed by alumae** 2020-09-25 12:12 UTC
